"use client";

import { useEffect } from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Image from "@tiptap/extension-image";
import Link from "@tiptap/extension-link";
import Underline from "@tiptap/extension-underline";
import TextAlign from "@tiptap/extension-text-align";
import Placeholder from "@tiptap/extension-placeholder";
import CharacterCount from "@tiptap/extension-character-count";
import TextStyle from "@tiptap/extension-text-style";
import FontFamily from "@tiptap/extension-font-family";
import Color from "@tiptap/extension-color";

const fonts=["Inter","Lora","Quicksand","Georgia","Arial","Courier New"];
function Button({active,disabled,onClick,children,title}:{active?:boolean;disabled?:boolean;onClick:()=>void;children:React.ReactNode;title:string}){return <button type="button" title={title} disabled={disabled} onClick={onClick} className={`inline-flex h-8 min-w-8 items-center justify-center rounded-md px-2 font-ui text-[11px] transition-colors disabled:opacity-40 ${active?"bg-ink text-sky":"text-ink-soft hover:bg-night/5 hover:text-ink"}`}>{children}</button>}

export default function RichTextEditor({value,onChange,uploadImage}:{value:string;onChange:(html:string)=>void;uploadImage:(file:File)=>Promise<string|null>}){
 const editor=useEditor({immediatelyRender:false,extensions:[StarterKit.configure({heading:{levels:[1,2,3]},codeBlock:false}),Underline,TextStyle,FontFamily,Color,Link.configure({openOnClick:false,autolink:true,defaultProtocol:"https"}),TextAlign.configure({types:["heading","paragraph"]}),Image.configure({inline:false,allowBase64:false}),Placeholder.configure({placeholder:"Write your story… Select text to style it, add headings, images and more."}),CharacterCount.configure({limit:50000})],content:value||"<p></p>",editorProps:{attributes:{class:"moonboy-editor-content min-h-[520px] px-6 py-6 font-body text-[16px] leading-8 text-ink outline-none"}},onUpdate:({editor:instance})=>onChange(instance.getHTML())});
 useEffect(()=>{if(editor && value!==editor.getHTML()) editor.commands.setContent(value||"<p></p>",false) },[editor,value]);
 if(!editor)return <div className="min-h-[540px] rounded-xl border border-line bg-surface"/>;
 async function addImage(file?:File){if(!file||!editor)return;const activeEditor=editor;const url=await uploadImage(file);if(url)activeEditor.chain().focus().setImage({src:url,alt:file.name}).run()}
 function addLink(){if(!editor)return;const current=editor.getAttributes("link").href;const url=window.prompt("Link URL",current||"https://");if(url===null)return;if(!url.trim())editor.chain().focus().unsetLink().run();else editor.chain().focus().setLink({href:url.trim()}).run()}
 return <div className="overflow-hidden rounded-xl border border-line bg-surface"><div className="sticky top-0 z-10 flex flex-wrap items-center gap-0.5 border-b border-line bg-[#f8f8f6] p-2 shadow-sm">
 <select title="Text style" value={editor.isActive("heading",{level:1})?"h1":editor.isActive("heading",{level:2})?"h2":editor.isActive("heading",{level:3})?"h3":"p"} onChange={e=>{const v=e.target.value;const c=editor.chain().focus();if(v==="p")c.setParagraph().run();else c.toggleHeading({level:Number(v[1]) as 1|2|3}).run()}} className="h-8 rounded-md border border-line bg-surface px-2 font-ui text-[10px] text-ink outline-none"><option value="p">Paragraph</option><option value="h1">Heading 1</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option></select>
 <select title="Font family" value={editor.getAttributes("textStyle").fontFamily||""} onChange={e=>editor.chain().focus().setFontFamily(e.target.value).run()} className="h-8 max-w-[125px] rounded-md border border-line bg-surface px-2 font-ui text-[10px] text-ink outline-none"><option value="">Default font</option>{fonts.map(font=><option key={font} value={font}>{font}</option>)}</select>
 <input title="Text color" type="color" value={editor.getAttributes("textStyle").color||"#1a1a2e"} onChange={e=>editor.chain().focus().setColor(e.target.value).run()} className="h-8 w-9 cursor-pointer rounded-md border border-line bg-surface p-1"/>
 <span className="mx-1 h-5 w-px bg-line/30"/><Button title="Bold" active={editor.isActive("bold")} onClick={()=>editor.chain().focus().toggleBold().run()}><strong>B</strong></Button><Button title="Italic" active={editor.isActive("italic")} onClick={()=>editor.chain().focus().toggleItalic().run()}><em>I</em></Button><Button title="Underline" active={editor.isActive("underline")} onClick={()=>editor.chain().focus().toggleUnderline().run()}><u>U</u></Button><Button title="Strike through" active={editor.isActive("strike")} onClick={()=>editor.chain().focus().toggleStrike().run()}>S̶</Button><Button title="Clear formatting" onClick={()=>editor.chain().focus().unsetAllMarks().clearNodes().run()}>Tx</Button>
 <span className="mx-1 h-5 w-px bg-line/30"/><Button title="Quote" active={editor.isActive("blockquote")} onClick={()=>editor.chain().focus().toggleBlockquote().run()}>“ ”</Button><Button title="Bullet list" active={editor.isActive("bulletList")} onClick={()=>editor.chain().focus().toggleBulletList().run()}>• list</Button><Button title="Numbered list" active={editor.isActive("orderedList")} onClick={()=>editor.chain().focus().toggleOrderedList().run()}>1.</Button><Button title="Horizontal rule" onClick={()=>editor.chain().focus().setHorizontalRule().run()}>—</Button>
 <span className="mx-1 h-5 w-px bg-line/30"/><Button title="Link" active={editor.isActive("link")} onClick={addLink}>↗</Button><label title="Insert image" className="inline-flex h-8 cursor-pointer items-center justify-center rounded-md px-2 font-ui text-[10px] text-ink-soft hover:bg-night/5">Image<input type="file" className="hidden" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{void addImage(e.target.files?.[0]);e.currentTarget.value=""}}/></label><Button title="Align left" onClick={()=>editor.chain().focus().setTextAlign("left").run()}>L</Button><Button title="Align center" onClick={()=>editor.chain().focus().setTextAlign("center").run()}>C</Button><Button title="Align right" onClick={()=>editor.chain().focus().setTextAlign("right").run()}>R</Button><Button title="Undo" disabled={!editor.can().undo()} onClick={()=>editor.chain().focus().undo().run()}>↶</Button><Button title="Redo" disabled={!editor.can().redo()} onClick={()=>editor.chain().focus().redo().run()}>↷</Button>
 </div><EditorContent editor={editor}/><div className="flex items-center justify-between border-t border-line px-4 py-2 font-ui text-[10px] text-ink-soft"><span>Live document · changes are reflected immediately</span><span>{editor.storage.characterCount.characters()} / 50,000</span></div></div>
}